### PR TITLE
test(fix): non workflow test

### PR DESCRIPTION
**Pull request by MyuddinKhatri**
After click on Yes in modal to submit document, wait for 2 seconds before closing the browser.

### CODE REVIEW

**Comment by agritheory** [comment]
@MyuddinKhatri We will want to run this test as a user who is assigned, a user with the correct role who is not assigned and a separate User Approval workflow.

**Comment by MyuddinKhatri** [comment]
The [test](https://github.com/agritheory/approvals/actions/runs/10165600514/job/28113772975?pr=64#step:15:1154) is failing at `waiting for locator("#approve-btn")` after navigating to Invoice page,

- To replicate this on local, do a fresh site installation and setup test data, directly run the tests without opening the site in the browser. (Once the site is open it loads the assets, it is able to locate the Approvals section as the script is loaded). 
OR This can be replicated by deleting the assets for approvals from the site folder and then run the tests
- Assets are not loaded for approvals in the browser when the test is executed first time on the site.
- Tried few ways (but didn't work) -
   - Added waiting before locating the button
   - added `bench build --app approvals` in CI before running tests
   - added init script before locating the button `page.add_init_script("/assets/approvals/dist/js/approvals.js")`

non_workflow_test

**Comment by agritheory** [comment]
@MyuddinKhatri Try adding a mutation observer to make sure the element exists before rendering it. (Taken from inventory_tools:faceted_search

```js

function waitForElement(selector) {
	return new Promise(resolve => {
		if (document.querySelector(selector)) {
			return resolve(document.querySelector(selector))
		}
		const observer = new MutationObserver(mutations => {
			if (document.querySelector(selector)) {
				resolve(document.querySelector(selector))
				observer.disconnect()
			}
		})
		observer.observe(document.body, {
			childList: true,
			subtree: true,
		})
	})
}
waitForElement('[data-route]').then(element => {
	const observer = new MutationObserver(() => {
		mount_list_view()
	})
	const config = { attributes: true, childList: false, characterData: true }
	observer.observe(element, config)
})


```

**Comment by MyuddinKhatri** [comment]
> @MyuddinKhatri Try adding a mutation observer to make sure the element exists before rendering it. (Taken from inventory_tools:faceted_search
> 
> ```js
> function waitForElement(selector) {
> 	return new Promise(resolve => {
> 		if (document.querySelector(selector)) {
> 			return resolve(document.querySelector(selector))
> 		}
> 		const observer = new MutationObserver(mutations => {
> 			if (document.querySelector(selector)) {
> 				resolve(document.querySelector(selector))
> 				observer.disconnect()
> 			}
> 		})
> 		observer.observe(document.body, {
> 			childList: true,
> 			subtree: true,
> 		})
> 	})
> }
> waitForElement('[data-route]').then(element => {
> 	const observer = new MutationObserver(() => {
> 		mount_list_view()
> 	})
> 	const config = { attributes: true, childList: false, characterData: true }
> 	observer.observe(element, config)
> })
> ```

@agritheory I tried this, but I think this will help us to just look for the button to appear, but in our case the button is not rendered in first place.

**Comment by agritheory** [comment]
@MyuddinKhatri  I think this is not related to Playwright. @fproldan reported that he saw this same behavior when navigating to a page for the first time - no approvals section appeared. Reload - it appears.

**Comment by MyuddinKhatri** [comment]
> @MyuddinKhatri I think this is not related to Playwright. @fproldan reported that he saw this same behavior when navigating to a page for the first time - no approvals section appeared. Reload - it appears.

Yes, I agree it doesn't seem to be related to Playwright, 
the behavior that it appears after reloading is it because of the build method used in this app? (Not sure about this)

**Comment by agritheory** [comment]
> > @MyuddinKhatri I think this is not related to Playwright. @fproldan reported that he saw this same behavior when navigating to a page for the first time - no approvals section appeared. Reload - it appears.
> 
> Yes, I agree it doesn't seem to be related to Playwright, the behavior that it appears after reloading is it because of the build method used in this app? (Not sure about this)

@MyuddinKhatri If you think it might be the timing of the build process, run `bench build` in the CI before we run `bench start`

**Comment by agritheory** [comment]
@MyuddinKhatri This appears to be working, can you rebase with the latest?

**Comment by MyuddinKhatri** [comment]
> @MyuddinKhatri This appears to be working, can you rebase with the latest?

@agritheory It is still failing, trying to locate the Approve button. I also added `bench build --app approvals` before `bench start` in CI this didn't work either.

**Pull request merged**
